### PR TITLE
generated mnemonic autocopy disabled & unlock button glitch fixed

### LINKED ISSUE #416: Disable autocopying mnemonic when generating a new one

### PR DESCRIPTION
**Pull request by bynjamin**
closes #416

### CODE REVIEW

File: app/frontend/components/pages/login/generateMnemonicDialog.js [hunk 1]
```diff
@@ -18,7 +19,7 @@ class GenerateMnemonicDialogClass {
         'The new wallet is created together with a mnemonic phrase. Write the mnemonic phrase down, you will need it to access your wallet. ',
         h('strong', undefined, 'Don’t copy it to your clipboard or save it anywhere online.')
       ),
-      h('div', {class: 'modal-mnemonic one-click-select'}, mnemonic),
+      h('div', {class: 'modal-mnemonic one-click-select'}, generateMnemonic()),
```
Comment (refi93) [inline app/frontend/components/pages/login/generateMnemonicDialog.js]: this isn't a good idea since re-rendering the component would trigger mnemonic regeneration. I would rather keep the previous logic but wipe the generated mnemonic from the state once the user closes the generate mnemonic dialog.

Comment (bynjamin) [reply app/frontend/components/pages/login/generateMnemonicDialog.js]: Ok , but it has to be different state parameter to avoid mnemonic field to be filled out on background and than cleared when user closes the window. It looks glitchy. For example generatedMnemonic.

**Comment by refi93** [comment]
When I fill some random characters in the mnemonic input and then I click "create new wallet" and the modal shows, the "Unlock" button becomes active (not greyed out) and it stays like that even after exiting the generate mnemonic modal. It may not be directly related to this PR but I would rather have it fixed as well.
