### PR TITLE
Fix Byron tests

### LINKED ISSUE #623: Failing unit tests in testnet branch
running `yarn test-chrome-headless` is currently failing on `testnet` branch. There are the folloring issues:

1. "Wallet Import" testes are failing with Unhandled promise rejection. It's probably caused by an outdated version of mocha and mocha-headless-chrome

2. Seven Byron-related unit tests are failing:
```
      successful transaction fee computation
        1) should compute the right transaction fee for given transaction
        2) should compute the right transaction fee for shorter outgoing address
      transaction serialization
        3) should properly serialize transaction before signing
        4) should properly discard utxos that cause an increase of fee higher than their value
        5) should properly compute transaction hash
        6) should properly serialize the whole transaction
      test transaction submission
        7) should properly submit transaction
```

### PR DESCRIPTION
**Pull request by elfinka**
1. for tests failing on getTxPlan:
getTxPlan expects just one argument, containing the values for address, coins and donationAmount. The original test code thus didn't provide any of these values and plan generation failed

2. Shelley testnet tests were failing on global leak detection - it seems the global Buffer causing the leaks is not needed (anymore)

3. Wallet import tests seem to be working fine

closes #623

### CODE REVIEW

File: app/frontend/helpers/wasmLoader.js [hunk 1]
```diff
@@ -1,10 +1,8 @@
-import {Buffer} from 'buffer'
 // interface extendedWindow extends Window {
 //   wasm?: any;
 // }
 
 export default async function loadWasmModule() {
   // (window as extendedWindow).wasm = await import('@emurgo/js-chain-libs/js_chain_libs_bg.wasm')
   window.wasm = await import('@emurgo/js-chain-libs/js_chain_libs_bg.wasm')
-  window.Buffer = Buffer
```
Comment (refi93) [inline app/frontend/helpers/wasmLoader.js:9]: @PeterBenc I see you commited this line in January 2020 - do you know why we needed it?

https://github.com/vacuumlabs/adalite/blob/4975453b030991f8fc6856f76d41c0ffcf004dbd/app/frontend/helpers/wasmLoader.js#L9

File: app/tests/src/cardano-wallet.js [hunk 2]
```diff
@@ -184,15 +184,21 @@ describe('successful transaction fee computation', () => {
...
     mockNet.clean()
   })
 
   it('should compute the right transaction fee for shorter outgoing address', async () => {
     const mockNet = mockNetwork(mockConfig2)
     mockNet.mockUtxoEndpoint()
 
-    assert.equal((await wallets.used.getTxPlan(shortAddress, 47, 0)).fee, 177838)
+    assert.equal(
+      (await wallets.used.getTxPlan({address: shortAddress, coins: 47, donationAmount: 0})).fee,
```
Comment (refi93) [inline app/tests/src/cardano-wallet.js:199]: @elfinka could you describe in the PR description what issue did you find in the tests and how do your changes address the problem(s)?

File: app/frontend/helpers/wasmLoader.js (hunk 1 above)
Comment (PeterBenc) [reply app/frontend/helpers/wasmLoader.js:9]: I remember trying something with it, I think it was a hotfix for something which was later solved properly. Its just a forgotten piece of code, to my knowledge the line is no longer useful for anything. I tested using the wasm library without this line and everything worked as expected.

File: app/tests/src/cardano-wallet.js (hunk 2 above)
Comment (elfinka) [reply app/tests/src/cardano-wallet.js:199]: Added description
