### PR TITLE
Empty config detection (check-types)

### LINKED ISSUE #327: Avoid running server with empty config
It causes weird behaviour (redirect loops since base url is not set, ...)

It would be nice to detect a missing config (e.g. non-presence of the  and kill the app with a comprehensive message. The options I see are either checking for presence of certain variables (a bit hacky approach), or to load the environment variables to a js object (see e.g. https://www.npmjs.com/package/config) and detect such required variables (failing if they are not available). Feel free to research best practices.

### PR DESCRIPTION
**Pull request by bynjamin**
closes #327

### CODE REVIEW

File: server/helpers/loadConfig.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+  ADALITE_MOCK_TX_SUBMISSION_SUCCESS,
+  ADALITE_MOCK_TX_SUMMARY_SUCCESS,
+  TREZOR_CONNECT_URL,
+  REDIS_URL,
+  STATS_PWD,
+  PORT,
+} = process.env
+
+const checkMap = check.map(
+  {
```
Comment (refi93) [inline server/helpers/loadConfig.js]: I would put there directly process.env and where integers need to be validated I would do something like this:
```
   ADALITE_DEFAULT_ADDRESS_COUNT: (x) => check.positive(parseInt(x, 10))
```
This should vastly eliminate the duplicity

File: server/helpers/isBoolStr.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+const boolStrings = ['true', 'false']
```
Comment (refi93) [inline server/helpers/isBoolStr.js]: I would not put the helper in a separate file since it is used only in one place and has quite a specific usecase

File: package.json [hunk 3]
```diff
@@ -41,6 +41,7 @@
   },
   "dependencies": {
     "body-parser": "^1.18.2",
+    "check-types": "^8.0.1",
```
Comment (refi93) [inline package.json]: until the fix is launched please revert to version 7.4.0

File: server/helpers/loadConfig.js [hunk 4]
```diff
@@ -0,0 +1,85 @@
+// config intended to be passed on to frontend
+// keys in process .env must be referencesd explicitly
```
Comment (refi93) [inline server/helpers/loadConfig.js]: typo: referencesd

File: server/helpers/loadConfig.js [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+  REDIS_URL,
+  STATS_PWD,
+  PORT,
+} = process.env
+
+const checkMap = check.map(process.env, {
+  ADALITE_ENABLE_DEBUGGING: isBoolString,
+  ADALITE_SERVER_URL: check.nonEmptyString,
+  ADALITE_BLOCKCHAIN_EXPLORER_URL: check.nonEmptyString,
+  ADALITE_DEFAULT_ADDRESS_COUNT: (x) => check.positive(parseInt(x, 10)),
```
Comment (refi93) [inline server/helpers/loadConfig.js]: I would extract that check to isPositiveIntString similarly as isBoolString

File: server/helpers/loadConfig.js [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+  ADALITE_GAP_LIMIT: (x) => check.positive(parseInt(x, 10)),
+  ADALITE_DEMO_WALLET_MNEMONIC: check.nonEmptyString,
+  ADALITE_ENABLE_TREZOR: isBoolString,
+  ADALITE_LOGOUT_AFTER: (x) => check.positive(parseInt(x, 10)),
+  ADALITE_ENABLE_SERVER_MOCKING_MODE: isBoolString,
+  ADALITE_MOCK_TX_SUBMISSION_SUCCESS: isBoolString,
+  ADALITE_MOCK_TX_SUMMARY_SUCCESS: isBoolString,
+})
```
Comment (refi93) [inline server/helpers/loadConfig.js]: I would validate PORT variable as well, since there is no default value for it

File: server/helpers/loadConfig.js [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+  TREZOR_CONNECT_URL,
+  REDIS_URL,
+  STATS_PWD,
+  PORT,
+} = process.env
+
+const checkMap = check.map(process.env, {
+  ADALITE_ENABLE_DEBUGGING: isBoolString,
+  ADALITE_SERVER_URL: check.nonEmptyString,
+  ADALITE_BLOCKCHAIN_EXPLORER_URL: check.nonEmptyString,
```
Comment (refi93) [inline server/helpers/loadConfig.js]: I would check whether it is an url, there is a validator for it in check-types AFAIK

Comment (bynjamin) [reply server/helpers/loadConfig.js]: webUrl predicate was removed in check-types version 3
